### ISSUE TITLE
More examples would be helpful 

### ISSUE THREAD

**Issue by moltar** [abdullah/vuex-module-generator#1]
Not very clear on how this is useful. I can see that it has a better structure and less boilerplate. But how does it fit into the whole project?

Thank you for your work!

**Comment by abdullah** [comment]
@moltar Hello! 

I've just published a customer example which shows you how to use a list state in diffrent cases.
This example contains implementation of crud module with `vuex-module-generator`, In additon, you can write other actions (update, create, delete). I hope it helps you to better understand :) 


https://abdullah.github.io/vuex-module-generator/

**Comment by moltar** [comment]
That's perfect!! Thank you!
